[package]
name = "blih"
version = "0.0.2"
authors = ["Zacharie Corniere <cornierez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12"

[dependencies.blih_rs]
path = "./blih_rs"

[dependencies.clap]
version = "~2.33"
features = ["yaml"]

[dependencies.reqwest]
version = "~0.10"
