[package]
name = "blih-rs"
version = "0.1.0"
authors = ["Zacharie Corniere <zacharie.corniere@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib_blih"
path = "src/lib/lib.rs"

[[bin]]
name = "blih"
path = "src/main.rs"

[dependencies]
rpassword = "4.0"
json = "0.12.1"
rust-crypto = "0.2"
hex = "0.4.1"

